#ifndef TOKENTYPE_H_
#define TOKENTYPE_H_
enum TokenType {
	start,
	// sign...
	SIGN_PLUS,
	SIGN_MINUS,
	SIGN_COLON,
	SIGN_STAR,
	SIGN_LESS,
	SIGN_GREATER,
	SIGN_EQUALS,
	SIGN_ASSIGN,
	SIGN_EQUALS_COLON_EQUALS,
	SIGN_EXCLAMATION,
	SIGN_AND,
	SIGN_SEMICOLON,
	SIGN_BRACKETOPEN,
	SIGN_BRACKETCLOSE,
	SIGN_BRACEOPEN,
	SIGN_BRACECLOSE,
	SIGN_SQUAREBRACKETOPEN,
	SIGN_SQUAREBRACKETCLOSE,
	SIGN_ERROR, // ?
	SIGN_COMPARE, // ?
	// comments
	COMMENT_START,
	COMMENT_END,
	ERROR, // error token
	INTEGER,
	IDENTIFIER,
	KEYWORD_WRITE,
	KEYWORD_READ,
	KEYWORD_IF,
	KEYWORD_ELSE,
	KEYWORD_WHILE,
	KEYWORD_INT
};
#endif
